#!/bin/sh
# File generated by ocamlbuild

cd /home/akshajgaur/Documents/VOQC-Python-Bindings

rm -f main.so
rm -f test.cmi
rm -f test.cmo
# Also clean the script itself
rm -f /home/akshajgaur/Documents/VOQC-Python-Bindings/_build/sanitize.sh
